[phases.setup]
nixPkgs = ["...", "php82", "php82Extensions.pdo_sqlite", "nodejs_18", "npm-9_x"]

[phases.build]
cmds = [
    "npm ci",
    "npm run build",
    "composer install --no-dev --optimize-autoloader"
]

[phases.start]
cmd = "php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"