# Nixpacks configuration for Railway deployment
[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci --production=false"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"