providers = ['node', 'php']

[phases.setup]
# Use nodejs-18_x which includes npm built-in - DO NOT install npm separately
nixPkgs = ['nodejs-18_x', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci --omit=dev'
]

[phases.build]
cmds = [
    'npm run build',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT'