# MINIMAL BUILD - NO UNNECESSARY SHIT
[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_20", "npm-9_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-scripts",
    "npm ci --production=false",
]

[phases.build] 
cmds = [
    # Copy environment example for artisan commands
    "cp .env.example .env",
    
    # Build frontend assets (skip if Vite fails - we use Blade templates)
    "npm run build || echo 'Vite build skipped - using Blade templates'",
    
    # Clear Laravel caches - NO CACHE BUILDING (it fails on Railway)
    "php artisan config:clear",
    "php artisan cache:clear", 
    "php artisan view:clear",
    "php artisan route:clear",
    
    # Create ONLY the directories we actually need
    "mkdir -p storage/logs",
    "mkdir -p bootstrap/cache",
    
    # Minimal permissions
    "chmod -R 775 storage bootstrap/cache",
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"