# Nixpacks configuration for Railway deployment

[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.ctype", "php82Extensions.json", "php82Extensions.bcmath", "php82Extensions.tokenizer", "php82Extensions.fileinfo", "php82Extensions.openssl", "php82Extensions.curl", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader",
    "npm ci",
    "npm run build"
]

[phases.build]
cmds = [
    # Clear all Laravel caches
    "php artisan cache:clear",
    "php artisan config:clear", 
    "php artisan route:clear",
    "php artisan view:clear",
    # Optimize for production
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    # Generate optimized autoload files
    "composer dump-autoload --optimize"
]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"