[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan cache:clear && php artisan config:cache && php artisan route:cache && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

[healthcheck]
path = "/up"
interval = 30
timeout = 10

[[services]]
name = "web"
port = 8080