[build]
builder = "nixpacks"

[deploy]
startCommand = "bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/up"
interval = 30
timeout = 10
maxRetries = 3