[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[healthcheck]
path = "/up"
interval = 30
timeout = 10
maxRetries = 3