[build]
builder = "nixpacks"
buildCommand = "composer install && npm ci && npm run build && php artisan optimize:clear"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"
healthcheckPath = "/up"
healthcheckTimeout = 30
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

[env]
APP_ENV = "production"
APP_DEBUG = "false"
LOG_CHANNEL = "stack"
LOG_LEVEL = "error"
SESSION_DRIVER = "cookie"
SESSION_LIFETIME = "120"
SESSION_ENCRYPT = "true"
SESSION_SECURE_COOKIE = "true"