[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev --optimize-autoloader && npm ci && npm run build && php artisan cache:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache"

[deploy]
startCommand = "php artisan migrate --force && php artisan cache:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan serve --host=0.0.0.0 --port=${PORT:-8080}"

[healthcheck]
path = "/up"
interval = 30
timeout = 10

[[services]]
name = "web"
port = 8080