/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./vendor/livewire/livewire/src/**/*.blade.php",
    "./vendor/livewire/livewire/config/livewire.php",
  ],
  safelist: [
    // Essential classes used in Livewire component
    'min-h-screen',
    'bg-gradient-to-br',
    'from-blue-50',
    'to-indigo-100',
    'py-8',
    'px-4',
    'sm:px-6',
    'lg:px-8',
    'max-w-7xl',
    'mx-auto',
    'text-center',
    'mb-8',
    'text-4xl',
    'font-bold',
    'text-gray-900',
    'mb-2',
    'text-lg',
    'text-gray-600',
    'grid',
    'grid-cols-1',
    'lg:grid-cols-2',
    'gap-6',
    'bg-white',
    'rounded-xl',
    'shadow-lg',
    'p-6',
    'mb-4',
    'block',
    'text-sm',
    'font-medium',
    'text-gray-700',
    'w-full',
    'px-3',
    'py-2',
    'border',
    'border-gray-300',
    'rounded-lg',
    'focus:ring-2',
    'focus:ring-blue-500',
    'focus:border-transparent',
    'resize-none',
    'bg-red-50',
    'border-red-200',
    'text-red-700',
    'grid-cols-3',
    'gap-4',
    'bg-gray-50',
    'p-3',
    'text-xs',
    'text-gray-500',
    'uppercase',
    'tracking-wide',
    'text-2xl',
    'font-semibold',
    'text-blue-600',
    'hover:text-blue-700',
    'transition-colors',
    'btn-transform',
    'btn-primary',
    'btn-secondary',
    'text-white',
    'hover:bg-blue-700',
    'flex',
    'items-center',
    'space-x-2',
    'rounded-md',
    'font-medium',
    'shadow',
    'hover:shadow-md'
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-down': 'slideDown 0.3s ease-out',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
      },
    },
  },
  plugins: [],
}
