/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./resources/**/*.blade.php",
    "./resources/**/*.js",
    "./resources/**/*.vue",
    "./vendor/livewire/livewire/src/**/*.blade.php",
    "./vendor/livewire/livewire/config/livewire.php",
  ],
  safelist: [
    // Revolutionary UI System Classes
    'transformation-grid',
    'primary-zone',
    'secondary-ring',
    'tertiary-layer',
    'btn-transform',
    'btn-style-guide',
    'io-container',
    'text-input',
    'stat-card',
    'stat-number',
    'stat-label',
    'btn-copy',
    'preview-overlay',
    'magnetic-zone',
    'gpu-accelerated',
    'smooth-rendering',
    'blur-glass',
    'text-gradient',
    'border-gradient',
    'loading-shimmer',
    'animate-magnetic-float',
    'animate-liquid-morph',
    'animate-text-transform',
    'animate-glow-pulse',
    'animate-slide-up',
    'animate-scale-in',
    'demo-uppercase',
    'demo-lowercase',
    'demo-title',
    'primary',
    'copied',
    // Color classes
    'text-neutral-0',
    'text-neutral-50',
    'text-neutral-100',
    'text-neutral-200',
    'text-neutral-300',
    'text-neutral-400',
    'text-neutral-500',
    'text-neutral-600',
    'text-neutral-700',
    'text-neutral-800',
    'text-neutral-900',
    'bg-neutral-0',
    'bg-neutral-50',
    'bg-neutral-100',
    'bg-neutral-200',
    'bg-neutral-300',
    'bg-accent-primary',
    'border-neutral-200',
    'border-neutral-300',
    'border-accent-primary',
    // Shadow classes
    'shadow-ambient',
    'shadow-micro',
    'shadow-low',
    'shadow-medium',
    'shadow-high',
    'shadow-primary',
    // Responsive grid
    'grid-magnetic'
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          50: '#eff6ff',
          100: '#dbeafe',
          200: '#bfdbfe',
          300: '#93c5fd',
          400: '#60a5fa',
          500: '#3b82f6',
          600: '#2563eb',
          700: '#1d4ed8',
          800: '#1e40af',
          900: '#1e3a8a',
          950: '#172554',
        },
        accent: {
          50: '#eef2ff',
          100: '#e0e7ff',
          200: '#c7d2fe',
          300: '#a5b4fc',
          400: '#818cf8',
          500: '#6366f1',
          600: '#4f46e5',
          700: '#4338ca',
          800: '#3730a3',
          900: '#312e81',
          950: '#1e1b4b',
        },
        neutral: {
          0: '#ffffff',
          50: '#fafafa',
          100: '#f5f5f5',
          200: '#e5e5e5',
          300: '#d4d4d4',
          400: '#a3a3a3',
          500: '#737373',
          600: '#525252',
          700: '#404040',
          800: '#262626',
          900: '#171717',
        },
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'Monaco', 'Consolas', 'Liberation Mono', 'Courier New', 'monospace'],
      },
      spacing: {
        'xs': '0.25rem',
        'sm': '0.5rem',
        'md': '1rem',
        'lg': '1.5rem',
        'xl': '2rem',
        '2xl': '3rem',
        '3xl': '4rem',
      },
      animation: {
        'fade-in': 'fadeIn 0.5s ease-in-out',
        'slide-down': 'slideDown 0.3s ease-out',
        'slide-up': 'slideUp 0.4s cubic-bezier(0.16, 1, 0.3, 1)',
        'scale-in': 'scaleIn 0.3s cubic-bezier(0.16, 1, 0.3, 1)',
        'magnetic-float': 'magneticFloat 6s ease-in-out infinite',
        'liquid-morph': 'liquidMorph 4s ease-in-out infinite',
        'text-transform': 'textTransform 0.6s cubic-bezier(0.25, 1, 0.5, 1)',
        'glow-pulse': 'glowPulse 3s ease-in-out infinite',
      },
      keyframes: {
        fadeIn: {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        slideDown: {
          '0%': { transform: 'translateY(-10px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        slideUp: {
          '0%': { transform: 'translateY(20px)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        scaleIn: {
          '0%': { transform: 'scale(0.95)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        magneticFloat: {
          '0%, 100%': { transform: 'translateY(0) rotate(0deg)' },
          '25%': { transform: 'translateY(-2px) rotate(0.5deg)' },
          '75%': { transform: 'translateY(-1px) rotate(-0.5deg)' },
        },
        liquidMorph: {
          '0%': { borderRadius: '12px' },
          '25%': { borderRadius: '16px 8px 12px 20px' },
          '50%': { borderRadius: '8px 16px 20px 12px' },
          '75%': { borderRadius: '20px 12px 8px 16px' },
          '100%': { borderRadius: '12px' },
        },
        textTransform: {
          '0%': { transform: 'scale(1) rotate(0deg)', opacity: '1' },
          '50%': { transform: 'scale(1.05) rotate(1deg)', opacity: '0.8' },
          '100%': { transform: 'scale(1) rotate(0deg)', opacity: '1' },
        },
        glowPulse: {
          '0%, 100%': { boxShadow: '0 0 20px rgba(99, 102, 241, 0.15)' },
          '50%': { boxShadow: '0 0 40px rgba(99, 102, 241, 0.25), 0 0 60px rgba(99, 102, 241, 0.15)' },
        },
      },
      boxShadow: {
        'ambient': '0 1px 3px rgba(0, 0, 0, 0.02)',
        'micro': '0 2px 8px rgba(0, 0, 0, 0.04)',
        'low': '0 4px 16px rgba(0, 0, 0, 0.06)',
        'medium': '0 8px 24px rgba(0, 0, 0, 0.08)',
        'high': '0 16px 40px rgba(0, 0, 0, 0.12)',
        'primary': '0 8px 32px rgba(99, 102, 241, 0.15)',
      },
      backdropBlur: {
        'xs': '2px',
        'sm': '4px',
        'md': '8px',
        'lg': '12px',
        'xl': '16px',
      },
    },
  },
  plugins: [
    function({ addUtilities }) {
      addUtilities({
        '.text-gradient': {
          'background': 'linear-gradient(135deg, var(--neutral-900) 0%, var(--neutral-600) 100%)',
          '-webkit-background-clip': 'text',
          '-webkit-text-fill-color': 'transparent',
          'background-clip': 'text',
        },
        '.blur-glass': {
          'backdrop-filter': 'blur(12px) saturate(1.8)',
          '-webkit-backdrop-filter': 'blur(12px) saturate(1.8)',
        },
        '.gpu-accelerated': {
          'transform': 'translateZ(0)',
          'will-change': 'transform',
          'backface-visibility': 'hidden',
          'perspective': '1000px',
        },
        '.smooth-rendering': {
          '-webkit-font-smoothing': 'antialiased',
          '-moz-osx-font-smoothing': 'grayscale',
          'text-rendering': 'optimizeLegibility',
        },
      });
    },
  ],
}
