<?php

/**
 * Category Configuration with Icons and Metadata
 * Complete mapping of all 18 categories with their tools, icons, and SEO metadata
 */

return [
    'categories' => [
        'case-conversions' => [
            'name' => 'Case Conversions',
            'slug' => 'case-conversions',
            'icon' => '🔤',
            'emoji' => '🔤',
            'svg_icon' => 'text-case',
            'color' => 'blue',
            'gradient' => 'from-blue-500 to-blue-600',
            'description' => 'Traditional text case transformations for any content',
            'meta_description' => 'Convert text to uppercase, lowercase, title case, sentence case and more. Professional text case conversion tools.',
            'keywords' => 'uppercase, lowercase, title case, sentence case, capitalize, alternating case, inverse case',
            'priority' => 1,
            'tool_count' => 7
        ],
        'developer-formats' => [
            'name' => 'Developer Formats',
            'slug' => 'developer-formats',
            'icon' => '💻',
            'emoji' => '💻',
            'svg_icon' => 'code',
            'color' => 'green',
            'gradient' => 'from-green-500 to-emerald-600',
            'description' => 'Programming and development text formats',
            'meta_description' => 'Convert text to camelCase, PascalCase, snake_case, kebab-case and other programming formats.',
            'keywords' => 'camelCase, PascalCase, snake_case, kebab-case, constant case, dot case, path case',
            'priority' => 2,
            'tool_count' => 12
        ],
        'journalistic-styles' => [
            'name' => 'Journalistic Styles',
            'slug' => 'journalistic-styles',
            'icon' => '📰',
            'emoji' => '📰',
            'svg_icon' => 'newspaper',
            'color' => 'gray',
            'gradient' => 'from-gray-600 to-gray-700',
            'description' => 'Professional journalism and media style guides',
            'meta_description' => 'AP Style, New York Times, Chicago, Guardian, BBC, Reuters journalism formatting tools.',
            'keywords' => 'AP style, New York Times style, Chicago style, Guardian style, BBC style, Reuters style',
            'priority' => 3,
            'tool_count' => 8
        ],
        'academic-styles' => [
            'name' => 'Academic Styles',
            'slug' => 'academic-styles',
            'icon' => '🎓',
            'emoji' => '🎓',
            'svg_icon' => 'academic-cap',
            'color' => 'purple',
            'gradient' => 'from-purple-500 to-purple-600',
            'description' => 'Academic and scholarly writing formats',
            'meta_description' => 'APA, MLA, Chicago, Harvard citation and academic writing style formatters.',
            'keywords' => 'APA style, MLA style, Chicago style, Harvard style, Vancouver style, IEEE style',
            'priority' => 4,
            'tool_count' => 9
        ],
        'creative-formats' => [
            'name' => 'Creative Formats',
            'slug' => 'creative-formats',
            'icon' => '✨',
            'emoji' => '✨',
            'svg_icon' => 'sparkles',
            'color' => 'pink',
            'gradient' => 'from-pink-500 to-rose-500',
            'description' => 'Fun and creative text transformations',
            'meta_description' => 'Creative text effects including reverse, aesthetic, sarcasm case, bubble text, and more.',
            'keywords' => 'reverse text, aesthetic text, sarcasm case, bubble text, script text, bold text',
            'priority' => 5,
            'tool_count' => 11
        ],
        'business-formats' => [
            'name' => 'Business Formats',
            'slug' => 'business-formats',
            'icon' => '💼',
            'emoji' => '💼',
            'svg_icon' => 'briefcase',
            'color' => 'indigo',
            'gradient' => 'from-indigo-500 to-indigo-600',
            'description' => 'Professional business communication styles',
            'meta_description' => 'Business email, legal documents, marketing headlines, press releases formatting tools.',
            'keywords' => 'email format, legal style, marketing headline, press release, memo, report, proposal',
            'priority' => 6,
            'tool_count' => 8
        ],
        'social-media-formats' => [
            'name' => 'Social Media',
            'slug' => 'social-media-formats',
            'icon' => '📱',
            'emoji' => '📱',
            'svg_icon' => 'share-social',
            'color' => 'cyan',
            'gradient' => 'from-cyan-500 to-blue-500',
            'description' => 'Optimized formats for social media platforms',
            'meta_description' => 'Format text for Twitter, Instagram, LinkedIn, Facebook, YouTube, TikTok and hashtags.',
            'keywords' => 'Twitter format, Instagram caption, LinkedIn post, Facebook style, YouTube title, hashtag generator',
            'priority' => 7,
            'tool_count' => 8
        ],
        'technical-documentation' => [
            'name' => 'Technical Docs',
            'slug' => 'technical-documentation',
            'icon' => '📚',
            'emoji' => '📚',
            'svg_icon' => 'document-text',
            'color' => 'orange',
            'gradient' => 'from-orange-500 to-amber-600',
            'description' => 'Technical writing and documentation formats',
            'meta_description' => 'API documentation, README, changelog, user manual, and technical specification formatters.',
            'keywords' => 'API docs, README format, changelog, user manual, technical spec, code comments',
            'priority' => 8,
            'tool_count' => 8
        ],
        'international-formats' => [
            'name' => 'International',
            'slug' => 'international-formats',
            'icon' => '🌍',
            'emoji' => '🌍',
            'svg_icon' => 'globe',
            'color' => 'teal',
            'gradient' => 'from-teal-500 to-cyan-600',
            'description' => 'Language and region-specific formatting',
            'meta_description' => 'British English, American English, Canadian, Australian, EU and ISO format converters.',
            'keywords' => 'British English, American English, Canadian English, Australian English, EU format, ISO format',
            'priority' => 9,
            'tool_count' => 8
        ],
        'utility-transformations' => [
            'name' => 'Utilities',
            'slug' => 'utility-transformations',
            'icon' => '🔧',
            'emoji' => '🔧',
            'svg_icon' => 'construct',
            'color' => 'yellow',
            'gradient' => 'from-yellow-500 to-amber-500',
            'description' => 'Practical text manipulation utilities',
            'meta_description' => 'Remove spaces, add dashes, extract letters, sort words, and other text utilities.',
            'keywords' => 'remove spaces, add dashes, remove punctuation, extract letters, sort words, word frequency',
            'priority' => 10,
            'tool_count' => 12
        ],
        'text-effects' => [
            'name' => 'Text Effects',
            'slug' => 'text-effects',
            'icon' => '🎨',
            'emoji' => '🎨',
            'svg_icon' => 'color-palette',
            'color' => 'red',
            'gradient' => 'from-red-500 to-pink-600',
            'description' => 'Visual text effects and stylized formatting',
            'meta_description' => 'Bold, italic, strikethrough, underline, superscript, subscript, and special text effects.',
            'keywords' => 'bold text, italic text, strikethrough, underline, superscript, subscript, upside down',
            'priority' => 11,
            'tool_count' => 12
        ],
        'generators' => [
            'name' => 'Generators',
            'slug' => 'generators',
            'icon' => '🎲',
            'emoji' => '🎲',
            'svg_icon' => 'dice',
            'color' => 'violet',
            'gradient' => 'from-violet-500 to-purple-600',
            'description' => 'Generate random data, passwords, IDs, and more',
            'meta_description' => 'Password generator, UUID generator, random numbers, Lorem Ipsum, and data generators.',
            'keywords' => 'password generator, UUID generator, random number, Lorem Ipsum, username generator',
            'priority' => 12,
            'tool_count' => 13
        ],
        'code-data-tools' => [
            'name' => 'Code & Data',
            'slug' => 'code-data-tools',
            'icon' => '⚙️',
            'emoji' => '⚙️',
            'svg_icon' => 'code-slash',
            'color' => 'slate',
            'gradient' => 'from-slate-600 to-slate-700',
            'description' => 'Formatters, converters, encoders for developers',
            'meta_description' => 'Binary translator, hex converter, JSON formatter, hash generators, and code formatting tools.',
            'keywords' => 'binary translator, hex converter, morse code, JSON formatter, MD5 hash, SHA256 hash',
            'priority' => 13,
            'tool_count' => 16
        ],
        'image-converters' => [
            'name' => 'Image Tools',
            'slug' => 'image-converters',
            'icon' => '🖼️',
            'emoji' => '🖼️',
            'svg_icon' => 'image',
            'color' => 'emerald',
            'gradient' => 'from-emerald-500 to-green-600',
            'description' => 'Image format conversion tools',
            'meta_description' => 'Convert JPG to PNG, PNG to WebP, ASCII art generator, and image conversion tools.',
            'keywords' => 'JPG to PNG, PNG to JPG, WebP converter, ASCII art, image converter',
            'priority' => 14,
            'tool_count' => 9
        ],
        'text-analysis' => [
            'name' => 'Text Analysis',
            'slug' => 'text-analysis',
            'icon' => '📊',
            'emoji' => '📊',
            'svg_icon' => 'stats-chart',
            'color' => 'lime',
            'gradient' => 'from-lime-500 to-green-600',
            'description' => 'Analyze and process text content',
            'meta_description' => 'Word counter, sentence counter, word frequency analyzer, duplicate finder tools.',
            'keywords' => 'word counter, sentence counter, word frequency, duplicate finder, text analyzer',
            'priority' => 15,
            'tool_count' => 8
        ],
        'text-cleanup' => [
            'name' => 'Text Cleanup',
            'slug' => 'text-cleanup',
            'icon' => '🧹',
            'emoji' => '🧹',
            'svg_icon' => 'trash',
            'color' => 'amber',
            'gradient' => 'from-amber-500 to-yellow-600',
            'description' => 'Clean and format text content',
            'meta_description' => 'Remove formatting, clean whitespace, remove characters, and text cleanup tools.',
            'keywords' => 'remove formatting, whitespace remover, plain text converter, text cleanup',
            'priority' => 16,
            'tool_count' => 8
        ],
        'social-media-generators' => [
            'name' => 'Social Fonts',
            'slug' => 'social-media-generators',
            'icon' => '✍️',
            'emoji' => '✍️',
            'svg_icon' => 'pencil',
            'color' => 'fuchsia',
            'gradient' => 'from-fuchsia-500 to-pink-600',
            'description' => 'Generate fonts for social media platforms',
            'meta_description' => 'Discord, Facebook, Instagram, Twitter font generators and social media text tools.',
            'keywords' => 'Discord font, Facebook font, Instagram font, Twitter font, social media fonts',
            'priority' => 17,
            'tool_count' => 8
        ],
        'miscellaneous' => [
            'name' => 'Miscellaneous',
            'slug' => 'miscellaneous',
            'icon' => '🎯',
            'emoji' => '🎯',
            'svg_icon' => 'apps',
            'color' => 'stone',
            'gradient' => 'from-stone-500 to-gray-600',
            'description' => 'Various utility and special tools',
            'meta_description' => 'NATO phonetic, Roman numerals, scientific notation, and miscellaneous text tools.',
            'keywords' => 'NATO phonetic, Roman numerals, scientific notation, special characters',
            'priority' => 18,
            'tool_count' => 7
        ]
    ],
    
    'featured_categories' => [
        'case-conversions',
        'developer-formats',
        'creative-formats',
        'generators'
    ],
    
    'popular_tools' => [
        'uppercase',
        'lowercase',
        'title-case',
        'camel-case',
        'snake-case',
        'password-generator',
        'lorem-ipsum',
        'word-counter'
    ]
];