<?php

/**
 * Tool Configuration
 * Complete mapping of all text transformation tools across 18 categories
 */

return [
        'case-conversions' => [
          'upper-case' => [
            'name' => 'Upper Case',
            'description' => 'Convert text to uppercase letters',
            'icon' => '🔤',
            'type' => 'case',
    ],
          'lower-case' => [
            'name' => 'Lower Case',
            'description' => 'Convert text to lowercase letters',
            'icon' => '🔡',
            'type' => 'case',
    ],
          'title-case' => [
            'name' => 'Title Case',
            'description' => 'Capitalize the first letter of each word',
            'icon' => '📝',
            'type' => 'case',
    ],
          'sentence-case' => [
            'name' => 'Sentence Case',
            'description' => 'Capitalize the first letter of each sentence',
            'icon' => '📄',
            'type' => 'case',
    ],
          'capitalize-words' => [
            'name' => 'Capitalize Words',
            'description' => 'Capitalize the first letter of every word',
            'icon' => '🔤',
            'type' => 'case',
    ],
          'alternating-case' => [
            'name' => 'Alternating Case',
            'description' => 'Alternate between uppercase and lowercase letters',
            'icon' => '🔀',
            'type' => 'case',
    ],
          'inverse-case' => [
            'name' => 'Inverse Case',
            'description' => 'Swap uppercase and lowercase letters',
            'icon' => '🔄',
            'type' => 'case',
    ],
  ],
        'developer-formats' => [
          'camel-case' => [
            'name' => 'Camel Case',
            'description' => 'Convert to camelCase format',
            'icon' => '🐪',
            'type' => 'case',
    ],
          'pascal-case' => [
            'name' => 'Pascal Case',
            'description' => 'Convert to PascalCase format',
            'icon' => '📦',
            'type' => 'case',
    ],
          'snake-case' => [
            'name' => 'Snake Case',
            'description' => 'Convert to snake_case format',
            'icon' => '🐍',
            'type' => 'case',
    ],
          'constant-case' => [
            'name' => 'Constant Case',
            'description' => 'Convert to CONSTANT_CASE format',
            'icon' => '📊',
            'type' => 'case',
    ],
          'kebab-case' => [
            'name' => 'Kebab Case',
            'description' => 'Convert to kebab-case format',
            'icon' => '🍢',
            'type' => 'case',
    ],
          'dot-case' => [
            'name' => 'Dot Case',
            'description' => 'Convert to dot.case format',
            'icon' => '⚫',
            'type' => 'case',
    ],
          'path-case' => [
            'name' => 'Path Case',
            'description' => 'Convert to path/case format',
            'icon' => '📁',
            'type' => 'case',
    ],
          'sql-case' => [
            'name' => 'SQL Case',
            'description' => 'Format for SQL queries',
            'icon' => '🗃️',
            'type' => 'case',
    ],
          'python-case' => [
            'name' => 'Python Case',
            'description' => 'Python naming convention',
            'icon' => '🐍',
            'type' => 'case',
    ],
          'java-case' => [
            'name' => 'Java Case',
            'description' => 'Java naming convention',
            'icon' => '☕',
            'type' => 'case',
    ],
          'php-case' => [
            'name' => 'PHP Case',
            'description' => 'PHP naming convention',
            'icon' => '🐘',
            'type' => 'case',
    ],
          'ruby-case' => [
            'name' => 'Ruby Case',
            'description' => 'Ruby naming convention',
            'icon' => '💎',
            'type' => 'case',
    ],
  ],
        'journalistic-styles' => [
          'ap-style' => [
            'name' => 'AP Style',
            'description' => 'Associated Press style guide',
            'icon' => '📰',
            'type' => 'style',
    ],
          'nyt-style' => [
            'name' => 'NY Times Style',
            'description' => 'New York Times style guide',
            'icon' => '🗞️',
            'type' => 'style',
    ],
          'chicago-style' => [
            'name' => 'Chicago Style',
            'description' => 'Chicago Manual of Style',
            'icon' => '📚',
            'type' => 'style',
    ],
          'guardian-style' => [
            'name' => 'Guardian Style',
            'description' => 'Guardian newspaper style',
            'icon' => '📰',
            'type' => 'style',
    ],
          'bbc-style' => [
            'name' => 'BBC Style',
            'description' => 'BBC News style guide',
            'icon' => '📺',
            'type' => 'style',
    ],
          'reuters-style' => [
            'name' => 'Reuters Style',
            'description' => 'Reuters news agency style',
            'icon' => '📡',
            'type' => 'style',
    ],
          'economist-style' => [
            'name' => 'Economist Style',
            'description' => 'The Economist style guide',
            'icon' => '📊',
            'type' => 'style',
    ],
          'wsj-style' => [
            'name' => 'WSJ Style',
            'description' => 'Wall Street Journal style',
            'icon' => '💼',
            'type' => 'style',
    ],
  ],
        'academic-styles' => [
          'apa-style' => [
            'name' => 'APA Style',
            'description' => 'American Psychological Association style',
            'icon' => '🎓',
            'type' => 'style',
    ],
          'mla-style' => [
            'name' => 'MLA Style',
            'description' => 'Modern Language Association style',
            'icon' => '📖',
            'type' => 'style',
    ],
          'chicago-author-date' => [
            'name' => 'Chicago Author-Date',
            'description' => 'Chicago author-date citation',
            'icon' => '📅',
            'type' => 'style',
    ],
          'chicago-notes' => [
            'name' => 'Chicago Notes',
            'description' => 'Chicago notes and bibliography',
            'icon' => '📝',
            'type' => 'style',
    ],
          'harvard-style' => [
            'name' => 'Harvard Style',
            'description' => 'Harvard referencing style',
            'icon' => '🏛️',
            'type' => 'style',
    ],
          'vancouver-style' => [
            'name' => 'Vancouver Style',
            'description' => 'Vancouver citation style',
            'icon' => '🏥',
            'type' => 'style',
    ],
          'ieee-style' => [
            'name' => 'IEEE Style',
            'description' => 'IEEE citation style',
            'icon' => '⚡',
            'type' => 'style',
    ],
          'ama-style' => [
            'name' => 'AMA Style',
            'description' => 'American Medical Association style',
            'icon' => '⚕️',
            'type' => 'style',
    ],
          'bluebook-style' => [
            'name' => 'Bluebook Style',
            'description' => 'Legal citation format',
            'icon' => '⚖️',
            'type' => 'style',
    ],
  ],
        'creative-formats' => [
          'vertical-text' => [
            'name' => 'Vertical Text',
            'description' => 'Display text vertically',
            'icon' => '📐',
            'type' => 'creative',
    ],
          'reversed-text' => [
            'name' => 'Reversed Text',
            'description' => 'Reverse the text order',
            'icon' => '⬅️',
            'type' => 'creative',
    ],
          'mirrored-text' => [
            'name' => 'Mirrored Text',
            'description' => 'Mirror the text horizontally',
            'icon' => '🪞',
            'type' => 'creative',
    ],
          'upside-down' => [
            'name' => 'Upside Down',
            'description' => 'Flip text upside down',
            'icon' => '🙃',
            'type' => 'creative',
    ],
          'diagonal-text' => [
            'name' => 'Diagonal Text',
            'description' => 'Display text diagonally',
            'icon' => '↗️',
            'type' => 'creative',
    ],
          'wave-text' => [
            'name' => 'Wave Text',
            'description' => 'Create wavy text effect',
            'icon' => '🌊',
            'type' => 'creative',
    ],
          'circle-text' => [
            'name' => 'Circle Text',
            'description' => 'Arrange text in a circle',
            'icon' => '⭕',
            'type' => 'creative',
    ],
          'zigzag-text' => [
            'name' => 'Zigzag Text',
            'description' => 'Create zigzag text pattern',
            'icon' => '⚡',
            'type' => 'creative',
    ],
          'pyramid-text' => [
            'name' => 'Pyramid Text',
            'description' => 'Arrange text in pyramid shape',
            'icon' => '🔺',
            'type' => 'creative',
    ],
          'spiral-text' => [
            'name' => 'Spiral Text',
            'description' => 'Create spiral text effect',
            'icon' => '🌀',
            'type' => 'creative',
    ],
          'rainbow-text' => [
            'name' => 'Rainbow Text',
            'description' => 'Add rainbow colors to text',
            'icon' => '🌈',
            'type' => 'creative',
    ],
  ],
        'business-formats' => [
          'email-format' => [
            'name' => 'Email Format',
            'description' => 'Professional email formatting',
            'icon' => '📧',
            'type' => 'format',
    ],
          'business-letter' => [
            'name' => 'Business Letter',
            'description' => 'Formal business letter format',
            'icon' => '✉️',
            'type' => 'format',
    ],
          'memo-format' => [
            'name' => 'Memo Format',
            'description' => 'Business memorandum format',
            'icon' => '📋',
            'type' => 'format',
    ],
          'invoice-format' => [
            'name' => 'Invoice Format',
            'description' => 'Professional invoice layout',
            'icon' => '🧾',
            'type' => 'format',
    ],
          'proposal-format' => [
            'name' => 'Proposal Format',
            'description' => 'Business proposal structure',
            'icon' => '📑',
            'type' => 'format',
    ],
          'resume-format' => [
            'name' => 'Resume Format',
            'description' => 'Professional resume layout',
            'icon' => '📄',
            'type' => 'format',
    ],
          'report-format' => [
            'name' => 'Report Format',
            'description' => 'Business report structure',
            'icon' => '📊',
            'type' => 'format',
    ],
          'contract-format' => [
            'name' => 'Contract Format',
            'description' => 'Legal contract formatting',
            'icon' => '📜',
            'type' => 'format',
    ],
  ],
        'social-media-formats' => [
          'twitter-thread' => [
            'name' => 'Twitter Thread',
            'description' => 'Format text for Twitter threads',
            'icon' => '🐦',
            'type' => 'social',
    ],
          'instagram-caption' => [
            'name' => 'Instagram Caption',
            'description' => 'Format Instagram captions',
            'icon' => '📸',
            'type' => 'social',
    ],
          'linkedin-post' => [
            'name' => 'LinkedIn Post',
            'description' => 'Professional LinkedIn formatting',
            'icon' => '💼',
            'type' => 'social',
    ],
          'facebook-post' => [
            'name' => 'Facebook Post',
            'description' => 'Format for Facebook posts',
            'icon' => '👍',
            'type' => 'social',
    ],
          'youtube-description' => [
            'name' => 'YouTube Description',
            'description' => 'Format YouTube descriptions',
            'icon' => '▶️',
            'type' => 'social',
    ],
          'tiktok-caption' => [
            'name' => 'TikTok Caption',
            'description' => 'Format TikTok captions',
            'icon' => '🎵',
            'type' => 'social',
    ],
          'reddit-post' => [
            'name' => 'Reddit Post',
            'description' => 'Format Reddit posts',
            'icon' => '🔴',
            'type' => 'social',
    ],
          'discord-message' => [
            'name' => 'Discord Message',
            'description' => 'Format Discord messages',
            'icon' => '💬',
            'type' => 'social',
    ],
  ],
        'technical-documentation' => [
          'markdown-format' => [
            'name' => 'Markdown Format',
            'description' => 'Convert to Markdown syntax',
            'icon' => '📝',
            'type' => 'documentation',
    ],
          'rst-format' => [
            'name' => 'RST Format',
            'description' => 'reStructuredText format',
            'icon' => '📄',
            'type' => 'documentation',
    ],
          'api-docs' => [
            'name' => 'API Docs',
            'description' => 'API documentation format',
            'icon' => '📡',
            'type' => 'documentation',
    ],
          'jsdoc-format' => [
            'name' => 'JSDoc Format',
            'description' => 'JavaScript documentation',
            'icon' => '📖',
            'type' => 'documentation',
    ],
          'javadoc-format' => [
            'name' => 'JavaDoc Format',
            'description' => 'Java documentation format',
            'icon' => '☕',
            'type' => 'documentation',
    ],
          'phpdoc-format' => [
            'name' => 'PHPDoc Format',
            'description' => 'PHP documentation format',
            'icon' => '🐘',
            'type' => 'documentation',
    ],
          'docstring-format' => [
            'name' => 'Docstring Format',
            'description' => 'Python docstring format',
            'icon' => '🐍',
            'type' => 'documentation',
    ],
          'sphinx-format' => [
            'name' => 'Sphinx Format',
            'description' => 'Sphinx documentation format',
            'icon' => '🔧',
            'type' => 'documentation',
    ],
  ],
        'international-formats' => [
          'british-english' => [
            'name' => 'British English',
            'description' => 'Convert to British spelling',
            'icon' => '🇬🇧',
            'type' => 'international',
    ],
          'american-english' => [
            'name' => 'American English',
            'description' => 'Convert to American spelling',
            'icon' => '🇺🇸',
            'type' => 'international',
    ],
          'canadian-english' => [
            'name' => 'Canadian English',
            'description' => 'Convert to Canadian spelling',
            'icon' => '🇨🇦',
            'type' => 'international',
    ],
          'australian-english' => [
            'name' => 'Australian English',
            'description' => 'Convert to Australian spelling',
            'icon' => '🇦🇺',
            'type' => 'international',
    ],
          'simplified-chinese' => [
            'name' => 'Simplified Chinese',
            'description' => 'Convert to simplified Chinese',
            'icon' => '🇨🇳',
            'type' => 'international',
    ],
          'traditional-chinese' => [
            'name' => 'Traditional Chinese',
            'description' => 'Convert to traditional Chinese',
            'icon' => '🇹🇼',
            'type' => 'international',
    ],
          'european-date' => [
            'name' => 'European Date',
            'description' => 'DD/MM/YYYY format',
            'icon' => '🇪🇺',
            'type' => 'international',
    ],
          'us-date' => [
            'name' => 'US Date',
            'description' => 'MM/DD/YYYY format',
            'icon' => '🇺🇸',
            'type' => 'international',
    ],
  ],
        'utility-transformations' => [
          'remove-spaces' => [
            'name' => 'Remove Spaces',
            'description' => 'Remove all spaces from text',
            'icon' => '🔽',
            'type' => 'utility',
    ],
          'trim-text' => [
            'name' => 'Trim Text',
            'description' => 'Remove leading and trailing spaces',
            'icon' => '✂️',
            'type' => 'utility',
    ],
          'add-line-numbers' => [
            'name' => 'Add Line Numbers',
            'description' => 'Number each line of text',
            'icon' => '🔢',
            'type' => 'utility',
    ],
          'remove-line-numbers' => [
            'name' => 'Remove Line Numbers',
            'description' => 'Remove line numbers from text',
            'icon' => '❌',
            'type' => 'utility',
    ],
          'sort-lines' => [
            'name' => 'Sort Lines',
            'description' => 'Sort lines alphabetically',
            'icon' => '📊',
            'type' => 'utility',
    ],
          'reverse-lines' => [
            'name' => 'Reverse Lines',
            'description' => 'Reverse the order of lines',
            'icon' => '🔄',
            'type' => 'utility',
    ],
          'unique-lines' => [
            'name' => 'Unique Lines',
            'description' => 'Remove duplicate lines',
            'icon' => '1️⃣',
            'type' => 'utility',
    ],
          'shuffle-lines' => [
            'name' => 'Shuffle Lines',
            'description' => 'Randomly shuffle lines',
            'icon' => '🎲',
            'type' => 'utility',
    ],
          'wrap-text' => [
            'name' => 'Wrap Text',
            'description' => 'Wrap text at specified width',
            'icon' => '📏',
            'type' => 'utility',
    ],
          'unwrap-text' => [
            'name' => 'Unwrap Text',
            'description' => 'Remove line breaks within paragraphs',
            'icon' => '📐',
            'type' => 'utility',
    ],
          'indent-text' => [
            'name' => 'Indent Text',
            'description' => 'Add indentation to text',
            'icon' => '➡️',
            'type' => 'utility',
    ],
          'outdent-text' => [
            'name' => 'Outdent Text',
            'description' => 'Remove indentation from text',
            'icon' => '⬅️',
            'type' => 'utility',
    ],
  ],
        'text-effects' => [
          'bold-text' => [
            'name' => 'Bold Text',
            'description' => 'Convert to bold Unicode characters',
            'icon' => '🅱️',
            'type' => 'effect',
    ],
          'italic-text' => [
            'name' => 'Italic Text',
            'description' => 'Convert to italic Unicode characters',
            'icon' => '📖',
            'type' => 'effect',
    ],
          'underline-text' => [
            'name' => 'Underline Text',
            'description' => 'Add underline to text',
            'icon' => '_',
            'type' => 'effect',
    ],
          'strike-through' => [
            'name' => 'Strike Through',
            'description' => 'Add strikethrough effect',
            'icon' => '➖',
            'type' => 'effect',
    ],
          'double-struck' => [
            'name' => 'Double Struck',
            'description' => 'Convert to double-struck characters',
            'icon' => '𝔻',
            'type' => 'effect',
    ],
          'cursive-text' => [
            'name' => 'Cursive Text',
            'description' => 'Convert to cursive Unicode',
            'icon' => '✍️',
            'type' => 'effect',
    ],
          'small-caps' => [
            'name' => 'Small Caps',
            'description' => 'Convert to small capital letters',
            'icon' => 'ᴀ',
            'type' => 'effect',
    ],
          'superscript' => [
            'name' => 'Superscript',
            'description' => 'Convert to superscript characters',
            'icon' => '²',
            'type' => 'effect',
    ],
          'subscript' => [
            'name' => 'Subscript',
            'description' => 'Convert to subscript characters',
            'icon' => '₂',
            'type' => 'effect',
    ],
          'wide-text' => [
            'name' => 'Wide Text',
            'description' => 'Convert to full-width characters',
            'icon' => '🅆',
            'type' => 'effect',
    ],
          'bubble-text' => [
            'name' => 'Bubble Text',
            'description' => 'Convert to bubble letters',
            'icon' => '🅾️',
            'type' => 'effect',
    ],
          'square-text' => [
            'name' => 'Square Text',
            'description' => 'Convert to square letters',
            'icon' => '🔲',
            'type' => 'effect',
    ],
  ],
        'generators' => [
          'lorem-ipsum' => [
            'name' => 'Lorem Ipsum',
            'description' => 'Generate Lorem Ipsum text',
            'icon' => '📝',
            'type' => 'generator',
    ],
          'random-text' => [
            'name' => 'Random Text',
            'description' => 'Generate random text',
            'icon' => '🎲',
            'type' => 'generator',
    ],
          'random-password' => [
            'name' => 'Random Password',
            'description' => 'Generate secure password',
            'icon' => '🔐',
            'type' => 'generator',
    ],
          'uuid-generator' => [
            'name' => 'UUID Generator',
            'description' => 'Generate unique identifier',
            'icon' => '🆔',
            'type' => 'generator',
    ],
          'random-name' => [
            'name' => 'Random Name',
            'description' => 'Generate random names',
            'icon' => '👤',
            'type' => 'generator',
    ],
          'random-email' => [
            'name' => 'Random Email',
            'description' => 'Generate random email addresses',
            'icon' => '📧',
            'type' => 'generator',
    ],
          'random-date' => [
            'name' => 'Random Date',
            'description' => 'Generate random dates',
            'icon' => '📅',
            'type' => 'generator',
    ],
          'random-color' => [
            'name' => 'Random Color',
            'description' => 'Generate random color codes',
            'icon' => '🎨',
            'type' => 'generator',
    ],
          'random-number' => [
            'name' => 'Random Number',
            'description' => 'Generate random numbers',
            'icon' => '🔢',
            'type' => 'generator',
    ],
          'random-ip' => [
            'name' => 'Random IP',
            'description' => 'Generate random IP addresses',
            'icon' => '🌐',
            'type' => 'generator',
    ],
          'random-url' => [
            'name' => 'Random URL',
            'description' => 'Generate random URLs',
            'icon' => '🔗',
            'type' => 'generator',
    ],
          'random-phone' => [
            'name' => 'Random Phone',
            'description' => 'Generate random phone numbers',
            'icon' => '📱',
            'type' => 'generator',
    ],
          'random-address' => [
            'name' => 'Random Address',
            'description' => 'Generate random addresses',
            'icon' => '🏠',
            'type' => 'generator',
    ],
  ],
        'code-data-tools' => [
          'json-format' => [
            'name' => 'JSON Format',
            'description' => 'Format and validate JSON',
            'icon' => '{ }',
            'type' => 'encoder',
    ],
          'json-minify' => [
            'name' => 'JSON Minify',
            'description' => 'Minify JSON data',
            'icon' => '📉',
            'type' => 'encoder',
    ],
          'json-escape' => [
            'name' => 'JSON Escape',
            'description' => 'Escape JSON strings',
            'icon' => '🔒',
            'type' => 'encoder',
    ],
          'json-unescape' => [
            'name' => 'JSON Unescape',
            'description' => 'Unescape JSON strings',
            'icon' => '🔓',
            'type' => 'encoder',
    ],
          'xml-format' => [
            'name' => 'XML Format',
            'description' => 'Format XML documents',
            'icon' => '📄',
            'type' => 'encoder',
    ],
          'xml-minify' => [
            'name' => 'XML Minify',
            'description' => 'Minify XML data',
            'icon' => '📉',
            'type' => 'encoder',
    ],
          'xml-escape' => [
            'name' => 'XML Escape',
            'description' => 'Escape XML entities',
            'icon' => '🔒',
            'type' => 'encoder',
    ],
          'xml-unescape' => [
            'name' => 'XML Unescape',
            'description' => 'Unescape XML entities',
            'icon' => '🔓',
            'type' => 'encoder',
    ],
          'html-encode' => [
            'name' => 'HTML Encode',
            'description' => 'Encode HTML entities',
            'icon' => '🌐',
            'type' => 'encoder',
    ],
          'html-decode' => [
            'name' => 'HTML Decode',
            'description' => 'Decode HTML entities',
            'icon' => '📖',
            'type' => 'encoder',
    ],
          'url-encode' => [
            'name' => 'URL Encode',
            'description' => 'URL encode text',
            'icon' => '🔗',
            'type' => 'encoder',
    ],
          'url-decode' => [
            'name' => 'URL Decode',
            'description' => 'URL decode text',
            'icon' => '🔓',
            'type' => 'encoder',
    ],
          'base64-encode' => [
            'name' => 'Base64 Encode',
            'description' => 'Encode to Base64',
            'icon' => '🔐',
            'type' => 'encoder',
    ],
          'base64-decode' => [
            'name' => 'Base64 Decode',
            'description' => 'Decode from Base64',
            'icon' => '🔑',
            'type' => 'encoder',
    ],
          'hex-encode' => [
            'name' => 'Hex Encode',
            'description' => 'Convert to hexadecimal',
            'icon' => '#',
            'type' => 'encoder',
    ],
          'binary-encode' => [
            'name' => 'Binary Encode',
            'description' => 'Convert to binary',
            'icon' => '01',
            'type' => 'encoder',
    ],
  ],
        'image-converters' => [
          'text-to-ascii-art' => [
            'name' => 'Text to ASCII Art',
            'description' => 'Convert text to ASCII art',
            'icon' => '🎨',
            'type' => 'converter',
    ],
          'image-to-base64' => [
            'name' => 'Image to Base64',
            'description' => 'Convert image to Base64',
            'icon' => '🖼️',
            'type' => 'converter',
    ],
          'svg-to-base64' => [
            'name' => 'SVG to Base64',
            'description' => 'Convert SVG to Base64',
            'icon' => '🎨',
            'type' => 'converter',
    ],
          'emoji-to-unicode' => [
            'name' => 'Emoji to Unicode',
            'description' => 'Convert emoji to Unicode',
            'icon' => '😀',
            'type' => 'converter',
    ],
          'unicode-to-emoji' => [
            'name' => 'Unicode to Emoji',
            'description' => 'Convert Unicode to emoji',
            'icon' => '🔣',
            'type' => 'converter',
    ],
          'text-to-qrcode' => [
            'name' => 'Text to QR Code',
            'description' => 'Generate QR code from text',
            'icon' => '📱',
            'type' => 'converter',
    ],
          'text-to-barcode' => [
            'name' => 'Text to Barcode',
            'description' => 'Generate barcode from text',
            'icon' => '📊',
            'type' => 'converter',
    ],
          'color-code-converter' => [
            'name' => 'Color Code Converter',
            'description' => 'Convert between color formats',
            'icon' => '🎨',
            'type' => 'converter',
    ],
          'font-converter' => [
            'name' => 'Font Converter',
            'description' => 'Convert between font formats',
            'icon' => '🔤',
            'type' => 'converter',
    ],
  ],
        'text-analysis' => [
          'word-counter' => [
            'name' => 'Word Counter',
            'description' => 'Count words in text',
            'icon' => '🔢',
            'type' => 'analysis',
    ],
          'character-counter' => [
            'name' => 'Character Counter',
            'description' => 'Count characters in text',
            'icon' => '📏',
            'type' => 'analysis',
    ],
          'line-counter' => [
            'name' => 'Line Counter',
            'description' => 'Count lines in text',
            'icon' => '📊',
            'type' => 'analysis',
    ],
          'reading-time' => [
            'name' => 'Reading Time',
            'description' => 'Calculate reading time',
            'icon' => '⏱️',
            'type' => 'analysis',
    ],
          'keyword-density' => [
            'name' => 'Keyword Density',
            'description' => 'Analyze keyword density',
            'icon' => '📈',
            'type' => 'analysis',
    ],
          'sentiment-analysis' => [
            'name' => 'Sentiment Analysis',
            'description' => 'Analyze text sentiment',
            'icon' => '😊',
            'type' => 'analysis',
    ],
          'readability-score' => [
            'name' => 'Readability Score',
            'description' => 'Calculate readability score',
            'icon' => '📖',
            'type' => 'analysis',
    ],
          'language-detector' => [
            'name' => 'Language Detector',
            'description' => 'Detect text language',
            'icon' => '🌐',
            'type' => 'analysis',
    ],
  ],
        'text-cleanup' => [
          'remove-duplicates' => [
            'name' => 'Remove Duplicates',
            'description' => 'Remove duplicate lines',
            'icon' => '🔄',
            'type' => 'cleanup',
    ],
          'remove-empty-lines' => [
            'name' => 'Remove Empty Lines',
            'description' => 'Remove blank lines',
            'icon' => '❌',
            'type' => 'cleanup',
    ],
          'remove-html-tags' => [
            'name' => 'Remove HTML Tags',
            'description' => 'Strip HTML from text',
            'icon' => '🏷️',
            'type' => 'cleanup',
    ],
          'remove-punctuation' => [
            'name' => 'Remove Punctuation',
            'description' => 'Remove all punctuation',
            'icon' => '.',
            'type' => 'cleanup',
    ],
          'remove-numbers' => [
            'name' => 'Remove Numbers',
            'description' => 'Remove all numbers',
            'icon' => '🔢',
            'type' => 'cleanup',
    ],
          'remove-special-chars' => [
            'name' => 'Remove Special Chars',
            'description' => 'Remove special characters',
            'icon' => '@',
            'type' => 'cleanup',
    ],
          'normalize-whitespace' => [
            'name' => 'Normalize Whitespace',
            'description' => 'Fix irregular spacing',
            'icon' => '📐',
            'type' => 'cleanup',
    ],
          'fix-encoding' => [
            'name' => 'Fix Encoding',
            'description' => 'Fix text encoding issues',
            'icon' => '🔧',
            'type' => 'cleanup',
    ],
  ],
        'social-media-generators' => [
          'hashtag-generator' => [
            'name' => 'Hashtag Generator',
            'description' => 'Generate relevant hashtags',
            'icon' => '#',
            'type' => 'generator',
    ],
          'twitter-font' => [
            'name' => 'Twitter Font',
            'description' => 'Special Twitter fonts',
            'icon' => '🐦',
            'type' => 'generator',
    ],
          'instagram-font' => [
            'name' => 'Instagram Font',
            'description' => 'Instagram bio fonts',
            'icon' => '📸',
            'type' => 'generator',
    ],
          'emoji-translator' => [
            'name' => 'Emoji Translator',
            'description' => 'Convert text to emojis',
            'icon' => '😀',
            'type' => 'generator',
    ],
          'bio-generator' => [
            'name' => 'Bio Generator',
            'description' => 'Generate social media bio',
            'icon' => '👤',
            'type' => 'generator',
    ],
          'caption-generator' => [
            'name' => 'Caption Generator',
            'description' => 'Generate post captions',
            'icon' => '💬',
            'type' => 'generator',
    ],
          'username-generator' => [
            'name' => 'Username Generator',
            'description' => 'Generate unique usernames',
            'icon' => '@',
            'type' => 'generator',
    ],
          'handle-checker' => [
            'name' => 'Handle Checker',
            'description' => 'Check username availability',
            'icon' => '✅',
            'type' => 'generator',
    ],
  ],
        'miscellaneous' => [
          'morse-code' => [
            'name' => 'Morse Code',
            'description' => 'Convert to/from Morse code',
            'icon' => '📡',
            'type' => 'misc',
    ],
          'binary-translator' => [
            'name' => 'Binary Translator',
            'description' => 'Convert to/from binary',
            'icon' => '01',
            'type' => 'misc',
    ],
          'roman-numerals' => [
            'name' => 'Roman Numerals',
            'description' => 'Convert to/from Roman numerals',
            'icon' => 'Ⅷ',
            'type' => 'misc',
    ],
          'nato-phonetic' => [
            'name' => 'NATO Phonetic',
            'description' => 'NATO phonetic alphabet',
            'icon' => '🎖️',
            'type' => 'misc',
    ],
          'pig-latin' => [
            'name' => 'Pig Latin',
            'description' => 'Convert to Pig Latin',
            'icon' => '🐷',
            'type' => 'misc',
    ],
          'leetspeak' => [
            'name' => 'Leetspeak',
            'description' => 'Convert to 1337 speak',
            'icon' => '1337',
            'type' => 'misc',
    ],
          'zalgo-text' => [
            'name' => 'Zalgo Text',
            'description' => 'Create glitchy text',
            'icon' => '👹',
            'type' => 'misc',
    ],
  ],
];
